- include: TLS.yml
  when: inventory_hostname == 'localhost'

- include: Node.yml
  when: inventory_hostname in groups['Node']

- include: KubernetesCoreAddons.yml
  when: inventory_hostname == 'localhost'

- include: calico.yml
  when: inventory_hostname in groups['Master']